# Generated by Django 5.2 on 2025-04-25 11:50

import django.db.models.deletion
import packages.id_generator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', packages.id_generator.UniqueIDField(default=packages.id_generator.uniqueID, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
