# Generated by Django 5.2 on 2025-04-25 12:11

import django.db.models.deletion
import packages.id_generator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', packages.id_generator.UniqueIDField(default=packages.id_generator.uniqueID, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Available'), ('B', 'Busy')], default='A', max_length=10)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='authentication.vendor')),
            ],
        ),
    ]
