# Generated by Django 5.2 on 2025-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('minivan', 'Minivan'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('motorcycle', 'Motorcycle'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='sedan', max_length=100),
        ),
    ]
