# Generated by Django 5.2 on 2025-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_driver_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='media/profile.png', null=True, upload_to='uploaded_files/kyc/photos/'),
        ),
    ]
