# Generated by Django 5.2 on 2025-04-25 13:33

import django.db.models.deletion
import packages.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('tank_id', packages.id_generator.UniqueIDField(default=packages.id_generator.uniqueID, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(blank=True, default='media/tank.png', null=True, upload_to='uploaded_files/tank/photos/')),
                ('tank_size', models.PositiveIntegerField()),
                ('tank_type', models.CharField(choices=[('Horizontal Water Tank', 'Horizontal Water Tank'), ('Vertical Water Tank', 'Vertical Water Tank'), ('IBC Water Tank', 'IBC Water Tank')], max_length=100)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='authentication.vendor')),
            ],
        ),
    ]
