# Generated by Django 5.2 on 2025-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='litres',
            field=models.CharField(blank=True, choices=[('500L', '500L'), ('750L', '750L'), ('1000L', '1000L'), ('1500L', '1500L'), ('2000L', '2000L'), ('2500L', '2500L'), ('3000L', '3000L')], max_length=100, null=True),
        ),
    ]
