# Generated by Django 5.2 on 2025-04-25 15:16

import django.db.models.deletion
import django.utils.timezone
import packages.id_generator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_tank_litres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', packages.id_generator.UniqueIDField(default=packages.id_generator.uniqueID, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Momo On Delivery', 'Momo On Delivery'), ('Cash On Delivery', 'Cash On Delivery')], max_length=100)),
                ('litres', models.CharField(max_length=100, null=True)),
                ('tank_type', models.CharField(choices=[('Horizontal Water Tank', 'Horizontal Water Tank'), ('Vertical Water Tank', 'Vertical Water Tank'), ('IBC Water Tank', 'IBC Water Tank')], max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('En Route', 'En Route'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', packages.id_generator.UniqueIDField(default=packages.id_generator.uniqueID, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Momo On Delivery', 'Momo On Delivery'), ('Cash On Delivery', 'Cash On Delivery')], max_length=30)),
                ('payment_status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], max_length=45)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='authentication.order')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', packages.id_generator.UniqueIDField(default=packages.id_generator.uniqueID, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('En Route', 'En Route'), ('Delivered', 'Delivered')], max_length=20)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleivered', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='authentication.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', packages.id_generator.UniqueIDField(default=packages.id_generator.uniqueID, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('rating', models.PositiveIntegerField()),
                ('text_review', models.TextField(max_length=500)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vendor')),
            ],
        ),
    ]
