# Generated by Django 5.2 on 2025-05-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_delivery_customer_lat_delivery_customer_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Pending Confirmation', 'Pending, Confirmation')], max_length=45),
        ),
    ]
